# Generated by Django 5.2.2 on 2025-06-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('full_description', models.TextField(blank=True, verbose_name='Повний опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна зі знижкою')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('colors', models.JSONField(blank=True, default=list, null=True, verbose_name='Доступні кольори')),
                ('sizes', models.JSONField(blank=True, default=list, null=True, verbose_name='Доступні розміри')),
                ('features', models.JSONField(blank=True, default=list, null=True, verbose_name='Особливості')),
                ('care_instructions', models.TextField(blank=True, null=True, verbose_name='Інструкції по догляду')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне зображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
                'ordering': ['order', 'id'],
            },
        ),
    ]
