# Generated by Django 5.2.2 on 2025-06-18 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоди'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Відсоток знижки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальна кількість використань'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мінімальна сума замовлення'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість використань'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Діє з'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Діє до'),
        ),
    ]
