# Generated by Django 5.2.2 on 2025-06-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ім’я')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('order', 'Питання по замовленню'), ('product', 'Питання по товару'), ('custom', 'Індивідуальне замовлення'), ('complaint', 'Скарги'), ('other', 'Інше')], max_length=20, verbose_name='Тема')),
                ('messenger', models.CharField(choices=[('empty', '---'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], default='empty', max_length=20, verbose_name='Месенджер')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
