# Generated by Django 5.2.2 on 2025-06-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='messenger',
            field=models.CharField(choices=[('empty', '---'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], default='empty', max_length=20, verbose_name='Месенджер'),
        ),
    ]
