# Generated by Django 5.2.2 on 2025-06-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер замовлення')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('confirmed', 'Підтверджено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ім’я')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_method', models.CharField(choices=[('courier', 'Кур’єрська доставка'), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Спосіб доставки')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('address', models.TextField(blank=True, verbose_name='Адреса доставки')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Поштовий індекс')),
                ('delivery_time', models.CharField(blank=True, max_length=20, verbose_name='Час доставки')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівкою при отриманні'), ('card', 'Карткою при отриманні'), ('online', 'Онлайн-оплата')], max_length=20, verbose_name='Спосіб оплати')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума товарів')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість доставки')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Разом')),
                ('notes', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна товару')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('selected_options', models.JSONField(blank=True, default=dict, verbose_name='Обрані опції')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
