# Generated by Django 5.2.2 on 2025-06-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='messengers',
            field=models.CharField(choices=[('empty', '---'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], default='empty', max_length=20, verbose_name='Месенджери для зв’язку'),
        ),
        migrations.AddField(
            model_name='order',
            name='office',
            field=models.CharField(default=1, verbose_name='№ відділення Нової Пошти'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Доставка Новою Поштою')], max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Накладений платіж (з попередньою передоплатою)'), ('card', 'Онлайн-оплата на карту')], max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
