# Generated by Django 5.2.2 on 2025-06-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_address_remove_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Доставка Новою Поштою')], default='nova_poshta', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='office',
            field=models.CharField(max_length=100, verbose_name='№ відділення Нової Пошти'),
        ),
    ]
